name: Detect EXIF Data

on:
  push:

jobs:
  detect-exif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install exiftool
        run: pip install detect-exif --break-system-packages
      
      - name: Scan for EXIF data in images
        run: |
            EXIT_CODE=0
            while read -rd $'\0' file; do
                ERR=0
                echo "Scanning $file for EXIF data..."
                detect-exif --quiet "$file" || ERR=1
                if [ $ERR -ne 0 ]; then   
                echo "ERROR: EXIF data found in $file"
                #   detect-exif "$file"
                EXIT_CODE=1
                fi
            done < <(find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.tiff" \) ! -path "./.git/*" -print0 )

            if [ $EXIT_CODE -eq 1 ]; then
                echo "❌ Workflow failed: Image files contain EXIF data"
                exit 1
            else
                echo "✅ No EXIF data found in image files"
            fi
